apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db 
    project: roboshop 
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db 
      project: roboshop 
  serviceName: "mongodb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db 
        project: roboshop
  spec: 
    containers:
    - name: gspvsr/mongodb:1.0.0
      image: mongodb
      volumeMounts:
      - name: mongodb
        mountPath: /data/db
  # this is PVC directly.
  volumeClaimTemplates:
  - metadata:
      name: mongodb
      namespace: roboshop
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  clusterIP: None #headless for databases
  selector:
    app: mongodb
    tier: db 
    project: roboshop 
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017 # this port belongs to service
    targetPort: 27017 # this port belongs to container