apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: mongodb:latest
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    app: mongodb
    tier: db
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017
